name: cursor_test_thread
description: "A Thread style SNS app"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 상태 관리
  provider: ^6.0.0
  get_it: ^7.6.0

  # 네비게이션
  go_router: ^12.0.0

  # UI/UX
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0

  # 이미지 관련
  image_picker: ^1.0.4
  photo_view: ^0.14.0

  # 무한 스크롤
  infinite_scroll_pagination: ^4.0.0

  # 기타
  cupertino_icons: ^1.0.2

  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 개발 도구
  flutter_lints: ^2.0.0
  logger: ^2.0.0

flutter:
  uses-material-design: true
